# Generated by Django 4.2.16 on 2026-05-08 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('version', models.CharField(max_length=20, verbose_name='Versão')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do arquivo .pkl')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Acurácia')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo ML',
                'verbose_name_plural': 'Modelos ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('protocol', models.CharField(blank=True, max_length=20, verbose_name='Protocolo')),
                ('packet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. pacotes')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duração (s)')),
                ('features_json', models.JSONField(verbose_name='Features de entrada')),
                ('prediction', models.CharField(choices=[('BENIGN', 'Benigno'), ('ATTACK', 'Ataque')], max_length=10, verbose_name='Predição')),
                ('attack_type', models.CharField(choices=[('BENIGN', 'Benigno'), ('SYN Flood', 'SYN Flood'), ('UDP Flood', 'UDP Flood'), ('HTTP Flood', 'HTTP Flood'), ('DNS Amplification', 'DNS Amplification'), ('Unknown', 'Desconhecido')], max_length=50, verbose_name='Tipo de ataque')),
                ('probability', models.FloatField(verbose_name='Probabilidade')),
                ('response_time_ms', models.FloatField(verbose_name='Tempo de resposta (ms)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_logs', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Log de Tráfego',
                'verbose_name_plural': 'Logs de Tráfego',
                'ordering': ['-timestamp'],
            },
        ),
    ]
